version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "somerootpassword"
      MYSQL_DATABASE: "notesdatabase"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "somepassword"
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
          - mysql_host
    driver: bridge
